### ISSUE TITLE
issue with install script

### ISSUE THREAD

**Issue by syncinggreen** [R0X4R/Garud#11]
┌──(root💀kali)-[~/Tools/Garud]
└─# sh install.sh
**: not found 3: 
: not found 9: 
install.sh: 10: cd: can't cd to /root
install.sh: 23: Syntax error: "elif" unexpected (expecting "then")**

**Comment by R0X4R** [comment]
Hi @syncinggreen,
I have fixed the code in the [new commit](https://github.com/R0X4R/Garud/commit/07b90122378eed1573818450db31ebcb74d54390). Now you can use the script to install all the tools.

regards,
**R0X4R**
