### ISSUE TITLE
Getting Error on running script

### ISSUE THREAD

**Issue by iampritam97** [R0X4R/Garud#13]
Getting the following error on running script 

Get-title: getting errors

![image](https://user-images.githubusercontent.com/38467538/109397480-cbea1580-795c-11eb-9eb3-a36d77662d35.png)

**Comment by R0X4R** [comment]
@iampritam97 thank you for raising this issue. I forgot to add get-title in the install.sh file. Now it fixed in the new commit. You can install it using

```
sudo go get -u github.com/tomnomnom/hacks/get-title && cp ~/go/bin/get-title /usr/bin/
```
