### ISSUE TITLE
assetfinder Getting errors

### ISSUE THREAD

**Issue by hangyakuzero** [R0X4R/Garud#14]
everytime i run the code the error pops up and the process   terminates
![Screenshot from 2021-03-09 21-46-21](https://user-images.githubusercontent.com/46108879/110510617-6569b200-8129-11eb-87d8-75301bfb40b1.png)

**Comment by R0X4R** [comment]
@hangyakuzero you need to install all the tools before using **Garud**. You can install assetfinder using

```
go get -u github.com/tomnomnom/assetfinder
```

or you can simply run **./install.sh**

regards,
R0X4R
