### ISSUE TITLE
Bad interpretor /bin/bash^M

### ISSUE THREAD

**Issue by mcharron** [R0X4R/Garud#20]
Hello,

After trying to install Garud, here's the error I got : 
`bash: ./install.sh : /bin/bash^M : bad interpretor: No such file or directory`

What I've done to fix : 
`sed -i -e 's/\r$//' install.sh`

After applying my fix, it worked.

**Comment by R0X4R** [comment]
Hii @mcharron,
This is the simple bash script issue. This issue occurs in some of the terminals, users can easily fix it by googling the issue. But really thank you for raising this issue I will add the fix method in readme.md file for those who get this error.

Thanks again,
Eshan Singh
