### ISSUE TITLE
install.sh problems

### ISSUE THREAD

**Issue by mcharron** [R0X4R/Garud#21]
`install.sh` line 45 : 
`cd ~/tools/ && wget https://github.com/projectdiscovery/httpx/releases/download/v1.0.6/httpx_1.0.6_linux_386.tar.gz && tar -xvf httpx_1.0.3_linux_386.tar.gz && mv httpx /usr/bin/`

Should be
`cd ~/tools/ && wget https://github.com/projectdiscovery/httpx/releases/download/v1.0.6/httpx_1.0.6_linux_386.tar.gz && tar -xvf httpx_1.0.6_linux_386.tar.gz && mv httpx /usr/bin/`

**Comment by R0X4R** [comment]
Hii @mcharron,
Thanks for raising this issue. I was forget to change the file name. Will fix it in next commit.

Thanks,
Eshan Singh
