### ISSUE TITLE
 bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by AmbitiousSam** [R0X4R/Garud#25]
when i run the install.sh file i get the following error:
```-bash: ./install.sh: /bin/bash^M: bad interpreter: No such file or directory```

**Comment by R0X4R** [comment]
Hii @AmbitiousSam,
Please do read the README.md file before installing the tool, I have already mentioned the fix for this error.

**Fix**
```rust
garud:~ sed -i -e 's/\r$//' install.sh
```

**Comment by AmbitiousSam** [comment]
Okay, My bad.
