### ISSUE TITLE
integration with https://xsshunter.com issues

### ISSUE THREAD

**Issue by n3whaze** [R0X4R/Garud#26]
Hello,
Is there any necessary conf to the tools works with xsshunter.com?

I tried garud -d hackerone.com -f hackerone -b MYDOMAINthere.xss.ht however I didn't receive the appropriate return. 

I tested a HTML file with the payloads in xsshunter.com and it worked well by itself

**Comment by R0X4R** [comment]
Hey @n3whaze,
Thanks for raising the issue. Can you please share the screenshot, because I checked on my target it's working completely fine, please share the screenshot.

Regards,
R0X4R
