### ISSUE TITLE
cannot run install.sh after chmod +x install.sh

### ISSUE THREAD

**Issue by dhrruvin** [R0X4R/Garud#27]
![image](https://user-images.githubusercontent.com/49072279/124435928-1cea9a00-dd93-11eb-8941-7fabc546c7d2.png)

**Comment by R0X4R** [comment]
Hi @dhrruvin,
Please read the [README.md](https://github.com/R0X4R/Garud#usage) file before installing.

Thanks,
R0X4R

**Comment by Dasil777** [comment]
- [ ]
