### ISSUE TITLE
Failed while testing for xss

### ISSUE THREAD

**Issue by Nithissh0708** [R0X4R/Garud#28]
Hey bro ,

while running the test it returned failed to dev/null 
And this directory not found /vulnerabilities/injection/xss.txt

**Comment by R0X4R** [comment]
Hii @Nithissh0708,
Thanks for raising this issue.

I think you're using an older code of Garud. Do update to the latest code of Garud. Then run the scan again.

Thanks,
R0X4R

**Comment by Nithissh0708** [comment]
I just used to install through binary source . Using git clone only . How to install latest one

**Comment by Nithissh0708** [comment]
This may help me out

**Comment by R0X4R** [comment]
Do run these commands

```js
garud:~ rm -rf /usr/bin/garud
garud:~ git clone https://github.com/R0X4R/Garud.git && cd Garud/ && chmod +x garud install.sh && mv garud /usr/bin/ && ./install.sh
```

**Comment by Nithissh0708** [comment]
again the error persist 
![Capture1](https://user-images.githubusercontent.com/77142588/125381103-2d2ce700-e348-11eb-8ea8-2ad8b8b98213.PNG)

**Comment by R0X4R** [comment]
Hii @Nithissh0708,
I'm sorry bro, actually I did some typo error in the code that's why you're getting this error. I have fixed the issue in the latest commit. Hope this will fix the issue.

Do run this command to install the latest commit
```js
garud:~ rm -rf /usr/bin/garud
garud:~ git clone https://github.com/R0X4R/Garud.git && cd Garud/ && chmod +x garud install.sh && mv garud /usr/bin/ && ./install.sh
```

Thanks,
R0X4R

**Comment by Nithissh0708** [comment]
And also please check sqli line it gives like dev/null not found . actually in code its looks like /dev/null

**Comment by R0X4R** [comment]
Hey @Nithissh0708,
I have already fixed the issue you're getting in the sqli line. Please do run the scan once and if the problem persists check your sqlmap, also do comment out that line.

Thanks,
R0X4R

**Comment by R0X4R** [comment]
Hi @Nithissh0708,
Is this fixed your issue so I can close this thread.

Thanks,
R0X4R

**Comment by Nithissh0708** [comment]
Yeah

**Comment by Nithissh0708** [comment]
Close the thread
