### ISSUE TITLE
Payload file name mismatch?

### ISSUE THREAD

**Issue by frost19k** [R0X4R/Garud#35]
Lines 11 & 12 in `install.sh` read as:
```bash
mv payloads/lfi.txt ~/tools/payloads/
mv payloads/ssti.txt ~/tools/payloads/
```

However lines 199 & 200 in `garud` read:
```bash
cat ~/tools/payloads/sstipayloads.txt | while read -r line; do cat domains/patterns/ssti.txt | qsreplace "$line" 2> /dev/null | anew -q temporary/ssti.txt;done
cat ~/tools/payloads/lfipayloads.txt | while read -r line; do cat domains/patterns/lfi.txt | qsreplace "$line" 2> /dev/null | anew -q temporary/lfi.txt;done
```
This produces a `file not found` error. 

Not sure if it's a file name mismatch or whether lfipayloads.txt & sstipayloads.txt are distinct from lfi.txt & ssti.txt

**Comment by R0X4R** [comment]
Hii @frost19k,

Thanks for raising the issue. I have fixed it in the latest commit do update your garud code.

Regards,
R0X4R

**Comment by frost19k** [comment]
No worries. While we're at it... line 215 in `garud` will fail with a `']' expected` error. There's a space missing after "nuclei/critical.txt".

I'm working on a Docker container for your script, been running each line to make sure everything works. :-)

**Comment by R0X4R** [comment]
ok fixed it :)
