### ISSUE TITLE
No Results

### ISSUE THREAD

**Issue by dabeer445** [R0X4R/Garud#37]
Hey,
I have installed all the dependecies but still whenever I run it on any target there is no result at all. Can you guide me what the issue seems to be?
![image](https://user-images.githubusercontent.com/9559114/144936703-8b0bc2ef-3991-4f81-9c3a-33e566c98fbf.png)

**Comment by frost19k** [comment]
Could you please delete all the files in `temporary` folder & run it again - just to make sure?

The way the script is written - if a file exists then the corresponding command does not run even if the file is empty. So I'm thinking it's possible you ran Garud as a test & it wrote an empty file & now it's skipping over those steps.

**Comment by R0X4R** [comment]
Please give new output folder or empty for every new scan

**Comment by dabeer445** [comment]
Hey The temp folder has the files but they are all empty
![image](https://user-images.githubusercontent.com/9559114/145481224-e97c5a16-ec39-47ea-8cb1-1047eb8c51a0.png)

the result screen
![image](https://user-images.githubusercontent.com/9559114/145481582-34b27e3a-85d7-4283-9e48-6cd37a6d02a8.png)

**Comment by R0X4R** [comment]
do update your garud and re-run it check if issue resolved or not sometimes domain is not vulnerable to any bug so it will show you this.

**Comment by FackJox** [comment]
I am running the latest garud version and also get the 0 subdomain error, the files mentioned above are created but have 0 content. 
I can run subfinder seperately and it retrieves subdomains however. I think the scan is not outputting in the files somehow. Anywhere I can dig deeper to get more info? Logs or tweak the garud go script to create some?

**Comment by R0X4R** [comment]
Hello @FackJox and @dabeer445 

I tried to fix it in new PR check if it works or not if not do open an issue again

Thanks
