### ISSUE TITLE
Update v3.2 in Docker

### ISSUE THREAD

**Issue by R0X4R** [R0X4R/Garud#43]
Hey @frost19k,
Greetings of the day

I have updated `garud` to **v3.2** can you please update the `dockerfile` and send me a PR.

**Latest release:** [`https://github.com/R0X4R/Garud/releases/tag/v3.2`](https://github.com/R0X4R/Garud/releases/tag/v3.2)

Thanks
R0X4R

**Comment by frost19k** [comment]
Sure. no worries.
