### ISSUE TITLE
getting this error

### ISSUE THREAD

**Issue by solo-hcker** [R0X4R/Garud#48]
![Screenshsdot_2022-01-05_10-47-20](https://user-images.githubusercontent.com/79417112/148164605-6af7c8c2-57a7-479c-a441-ce826dedcc6d.png)

i used command "garud -d domain.com  -o myfile -b mydomain.xss.ht

**Comment by Varsus808** [comment]
Ran into the same issue, its an error message from the notify project over at https://github.com/projectdiscovery/notify .
How to make the file and what it does is detailed in the read me.
