### ISSUE TITLE
issues file not found database/urls.tct

### ISSUE THREAD

**Issue by 0xHani** [R0X4R/Garud#52]
![image](https://user-images.githubusercontent.com/66733155/174199331-7e04b1b3-813d-4288-b364-97c928288ef3.png)

**Comment by R0X4R** [comment]
Hii @0xHani,

Could you please check that all the necessary tools are installed in your system I think the issue is in your system not in the script.

Please check then let me know.

**Comment by 0xHani** [comment]
i install all the tool when its in subdomain scanning its take a lot of time and show nothing
![image](https://user-images.githubusercontent.com/66733155/174354868-918c0041-1d96-4f17-8b19-45844e6147d8.png)

**Comment by bthrx** [comment]
I have this issue as well. Looking at my amass.log I can tell Garud is indeed running it but doesn't appear to be outputting to the database/urls.txt. I glanced at the install.sh but couldn't find any of the mkdir directories on my system but hadn't dug in on that completely yet.

**Comment by R0X4R** [comment]
Hello @0xHani and @bthrx 

I tried to fix it in new PR check if it works or not if not do open an issue again 

Thanks
