### ISSUE TITLE
Issue at installation /usr/bin/env: ‘bash\r’: No such file or directory

### ISSUE THREAD

**Issue by C0NQR0R** [R0X4R/Garud#53]
/usr/bin/env: ‘bash\r’: No such file or directory
# 
![Capture](https://user-images.githubusercontent.com/102713486/178096873-e3c8b8e0-9bc9-46fb-847b-f464e36fcde8.PNG)
#

**Comment by tusherh82** [comment]
### **I'm face exactly same.**
1. **First of all open the install.sh script in nano:** `sudo nano install.sh`
In the first line of the script looks like this: `#!/usr/bin/env bash`
2. **Change to this:** `#!/bin/bash`
3. **Click:** `ctrl+x`
4. **Then click:** `y` 
5. **Press:** `Enter` (For save the file)
6. **Now, run this fix command:** `sudo sed -i -e 's/\r$//' install.sh`

**Your problem solved here.........**
**But, You'll come back with other problem. the problem solution shown below:**

**Big fix:**
1. Open the **install.sh** script in any editor. I'm using **gedit**. Command: `sudo gedit install.sh`
2. Remove this code from entire script: `> /dev/null 2>&1`

It'll show verbose of all commands. You can check where the problem occurs for running the install.sh script.

**Comment by R0X4R** [comment]
Hi @C0NQR0R 

Please read the README.md file you'll get the solution. And @tusherh82 thank you for your solution :)
