### ISSUE TITLE
Tools get-title missing

### ISSUE THREAD

**Issue by ulises2k** [R0X4R/Garud#9]
Where download "get-title" ?

**Comment by R0X4R** [comment]
you can use ``go get -u github.com/tomnomnom/hacks/get-title`` to install the tool.

**Comment by ulises2k** [comment]
404, page not found

**Comment by R0X4R** [comment]
[hacks/get-title at master · tomnomnom/hacks · GitHub](https://github.com/tomnomnom/hacks/tree/master/get-title)
Link
